name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Lua 5.1 and LuaRocks
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.1 luarocks

    - name: Install dependencies
      run: |
        sudo luarocks install luaunit
        sudo luarocks install luacov

    - name: Run tests
      run: lua5.1 Tests/RunTests.lua
